#' @title Perform Bulk EEM Plotting
#'
#' @author Robert Lee
#'
#' @details When a folder containing corrected EEMs \emph{somewhere} in it is passed to the function,
#' plots for all found EEMs are saved. The folder structure inside the directory is replicated in a
#' 'plots' directory inside the given EEM folder\cr
#' \cr
#'
#' @param \code{eem.dir} - A directory containing previosuly corrected EEMs, generated by the \code{f4.eem.correct}
#' function. Will search recursively through the directory for corrected EEMs. Corrected EEMs have file names ending in "_c.csv"
#' @param \code{rayliegh.mask} - Should 1st and 2nd order Rayliegh scattering be masked? Defaults to TRUE.
#' @param \code{white.mask} - Should masked values be drawn white? Defaults to TRUE.
#'
#' @return EEM plots are saved in a plots folder, inside the directory given to \code{eem.dir}.
#'
#' @example
#'
#' @export
#'

batch.plot=function(eem.dir, rayliegh.mask=T, white.mask=T){

    ## Bulk EEM plotting
    eems=list.files(path = eem.dir, pattern = "_c.csv", recursive = T, full.names = T) #find all corrected files
    names=stringr::str_split(string = eems, pattern = "/") #get names of files
    names=unlist(lapply(names, function(x) x[[length(x)]])) #more name stuff
    names=gsub(pattern = "_c.csv", replacement = "", x = names)

    save.dir=paste0(eem.dir, "/plots/")
    if(!dir.exists(save.dir)){dir.create(save.dir)}


    #this bit plots them all
    if(rayliegh.mask){
        lapply(seq(length(eems)), function(x) eem.plot(corr.eem = fluoro::rayleigh.mask(eem=read.corr.eem(eems[x]), mask.value = 0),
                                                       sample.name = names[x],
                                                       save.dir = save.dir, white.mask=white.mask))
    }else if(rayliegh.mask==F){
        lapply(seq(length(eems)), function(x) eem.plot(corr.eem = read.corr.eem(eems[x]),
                                                       sample.name = names[x],
                                                       save.dir = save.dir, white.mask = white.mask))
    }
}
