#' @title Calculate the Fluorecence Index (FI) for a corrected EEM
#'
#' @author Robert Lee <rhlee@colorado.edu>
#'
#' @details Adapted from the original Matlab F4CorrectFunII, authored by Laurel Larsen, (5/25/07),
#' Kaelin Cawley (6/18/09), Rachel Gabor, Bailey Simone, and Mike SanClements (April 2010).
#'
#'
#' @param \code{corr.eem} - A previosuly corrected EEM, generated by the \code{f4.eem.correct}
#' function. If the EEM isn't loaded, read it in with the \code{read.corr.eem} function.
#'
#' @return The FI value for the corrected EEM.
#'
#' @examples
#'\dontrun{
#' eem=read.corr.eem("../A4575E_c.csv")
#' FI=fi.calc(eem)
#'}
#'
#' @export
#'

fi.calc=function(corr.eem){
  FI=round(
      corr.eem[row.names(corr.eem)==470,
                    colnames(corr.eem)==370]/corr.eem[row.names(corr.eem)==520,
                                                      colnames(corr.eem)==370],
      digits = 3)
  return(FI)
}
