#' @title Perform PARAFAC Modeling on Corrected EEMs
#'
#' @author Robrt Lee
#'
#' @details Will expand an EEM to 1nm incriements in both directions,
#' and returns the calculated freshness index.
#'
#' @param \code{corr.eem} - A previosuly corrected EEM, generated by the \code{f4.eem.correct}
#' function. If the EEM isn't loaded, read it in with the \code{read.corr.eem} function.
#'
#'
#' @return The freshenss index value
#'
#' @example
#' \dontrun{
#' fresh.calc(eem)
#' }
#'
#' @export
#'
#'
#'

fresh.calc=function(corr.eem){

    exp.eem=fluoro::expand.eem(corr.eem)

    fresh = round(exp.eem[
        which(rownames(exp.eem)=="380"),
        colnames(exp.eem)=="310"]/

            max(
                exp.eem[(as.numeric(rownames(exp.eem))>=420&
                             436>=as.numeric(rownames(exp.eem))),
                        colnames(exp.eem)=="310"]
            ), digits = 3
    )

    return(fresh)
}
