#' @title Read in an EEM File Generated by a Fluoromax F3
#'
#' @author Robert Lee
#'
#' @details This function reads in raw EEMs produced by the F3, as an XLS file.
#' A correctly formatted EEM is returned for use with other functions in the 'fluoro' package.
#'
#' @param \code{f3.eem.file} - A character path pointing to the EEM file.
#' File must be an xls file output by the Fluoromax software.
#'
#' @return A properly formatted EEM, as a data frame.
#'
#' @export
#'

read.f3.eem=function(f3.eem.file){
    library(magrittr)
    options(stringsAsFactors = F)
    raw.f3=readxl::read_excel(path = f3.eem.file, sheet = 1, col_names = F) # Read in the XLS file
    trim.f3=as.data.frame(raw.f3[which(rowSums(is.na(raw.f3))==0)[1]:nrow(raw.f3),]) # Lop off the header

    cnames=trim.f3[1,-1]
    rnames=trim.f3[2:nrow(trim.f3),1]

    f3.eem=trim.f3[-1, -1] %>% `colnames<-`(value=cnames) %>% `rownames<-`(value=rnames) #clean up the eem
    return(f3.eem)
}
